Name:Adithya Rao Kalathur

Reg No: 251100610012

Branch: M.E. CSE

# **Q3**

**(a) Apply logistic regression algorithm for the given dataset.**

**(b) Analyse the result of the logistic regression algorithm for the given dataset.**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
data=pd.read_csv('/content/drive/MyDrive/AGAI&ML Lab Midsem Dataset/iris 2.csv', header=None)
data = data[0].str.split(',', expand=True)

In [ ]:
data

5.1,3.5,1.4,0.2,Iris-setosa
0       4.9,3.0,1.4,0.2,Iris-setosa
1       4.7,3.2,1.3,0.2,Iris-setosa
2       4.6,3.1,1.5,0.2,Iris-setosa
3       5.0,3.6,1.4,0.2,Iris-setosa
4       5.4,3.9,1.7,0.4,Iris-setosa
..                              ...
144  6.7,3.0,5.2,2.3,Iris-virginica
145  6.3,2.5,5.0,1.9,Iris-virginica
146  6.5,3.0,5.2,2.0,Iris-virginica
147  6.2,3.4,5.4,2.3,Iris-virginica
148  5.9,3.0,5.1,1.8,Iris-virginica

[149 rows x 1 columns]

In [ ]:
x=data.iloc[:,:4].values
x

array([['5.1', '3.5', '1.4', '0.2'],
       ['4.9', '3.0', '1.4', '0.2'],
       ['4.7', '3.2', '1.3', '0.2'],
       ['4.6', '3.1', '1.5', '0.2'],
       ['5.0', '3.6', '1.4', '0.2'],
       ['5.4', '3.9', '1.7', '0.4'],
       ['4.6', '3.4', '1.4', '0.3'],
       ['5.0', '3.4', '1.5', '0.2'],
       ['4.4', '2.9', '1.4', '0.2'],
       ['4.9', '3.1', '1.5', '0.1'],
       ['5.4', '3.7', '1.5', '0.2'],
       ['4.8', '3.4', '1.6', '0.2'],
       ['4.8', '3.0', '1.4', '0.1'],
       ['4.3', '3.0', '1.1', '0.1'],
       ['5.8', '4.0', '1.2', '0.2'],
       ['5.7', '4.4', '1.5', '0.4'],
       ['5.4', '3.9', '1.3', '0.4'],
       ['5.1', '3.5', '1.4', '0.3'],
       ['5.7', '3.8', '1.7', '0.3'],
       ['5.1', '3.8', '1.5', '0.3'],
       ['5.4', '3.4', '1.7', '0.2'],
       ['5.1', '3.7', '1.5', '0.4'],
       ['4.6', '3.6', '1.0', '0.2'],
       ['5.1', '3.3', '1.7', '0.5'],
       ['4.8', '3.4', '1.9', '0.2'],
       ['5.0', '3.0', '1.6', '0.2'],
       ['5.0', '3.4', '1.6', '0.4'],
 

In [ ]:
y=data.iloc[:,4].values
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_encoded = le.fit_transform(y)
y_encoded

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y_encoded,test_size=0.35,random_state=0)

In [ ]:
x_train

array([['5.5', '2.4', '3.8', '1.1'],
       ['6.3', '2.7', '4.9', '1.8'],
       ['6.3', '2.8', '5.1', '1.5'],
       ['4.9', '2.5', '4.5', '1.7'],
       ['6.3', '2.5', '5.0', '1.9'],
       ['7.0', '3.2', '4.7', '1.4'],
       ['6.5', '3.0', '5.2', '2.0'],
       ['6.0', '3.4', '4.5', '1.6'],
       ['4.8', '3.1', '1.6', '0.2'],
       ['5.8', '2.7', '5.1', '1.9'],
       ['5.6', '2.7', '4.2', '1.3'],
       ['5.6', '2.9', '3.6', '1.3'],
       ['5.5', '2.5', '4.0', '1.3'],
       ['6.1', '3.0', '4.6', '1.4'],
       ['7.2', '3.2', '6.0', '1.8'],
       ['5.3', '3.7', '1.5', '0.2'],
       ['4.3', '3.0', '1.1', '0.1'],
       ['6.4', '2.7', '5.3', '1.9'],
       ['5.7', '3.0', '4.2', '1.2'],
       ['5.4', '3.4', '1.7', '0.2'],
       ['5.7', '4.4', '1.5', '0.4'],
       ['6.9', '3.1', '4.9', '1.5'],
       ['4.6', '3.1', '1.5', '0.2'],
       ['5.9', '3.0', '5.1', '1.8'],
       ['5.1', '2.5', '3.0', '1.1'],
       ['4.6', '3.4', '1.4', '0.3'],
       ['6.2', '2.2', '4.5', '1.5'],
 

In [ ]:
x_test

array([['5.8', '2.8', '5.1', '2.4'],
       ['6.0', '2.2', '4.0', '1.0'],
       ['5.5', '4.2', '1.4', '0.2'],
       ['7.3', '2.9', '6.3', '1.8'],
       ['5.0', '3.4', '1.5', '0.2'],
       ['6.3', '3.3', '6.0', '2.5'],
       ['5.0', '3.5', '1.3', '0.3'],
       ['6.7', '3.1', '4.7', '1.5'],
       ['6.8', '2.8', '4.8', '1.4'],
       ['6.1', '2.8', '4.0', '1.3'],
       ['6.1', '2.6', '5.6', '1.4'],
       ['6.4', '3.2', '4.5', '1.5'],
       ['6.1', '2.8', '4.7', '1.2'],
       ['6.5', '2.8', '4.6', '1.5'],
       ['6.1', '2.9', '4.7', '1.4'],
       ['4.9', '3.1', '1.5', '0.1'],
       ['6.0', '2.9', '4.5', '1.5'],
       ['5.5', '2.6', '4.4', '1.2'],
       ['4.8', '3.0', '1.4', '0.3'],
       ['5.4', '3.9', '1.3', '0.4'],
       ['5.6', '2.8', '4.9', '2.0'],
       ['5.6', '3.0', '4.5', '1.5'],
       ['4.8', '3.4', '1.9', '0.2'],
       ['4.4', '2.9', '1.4', '0.2'],
       ['6.2', '2.8', '4.8', '1.8'],
       ['4.6', '3.6', '1.0', '0.2'],
       ['5.1', '3.8', '1.9', '0.4'],
 

In [ ]:
#standard scalar
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train_scaled=sc.fit_transform(x_train)
x_test_scaled=sc.transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(random_state=0)
model.fit(x_train_scaled,y_train)

LogisticRegression(random_state=0)

In [ ]:
y_pred=model.predict(x_test_scaled)


In [ ]:

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[16,  0,  0],
       [ 0, 20,  1],
       [ 0,  2, 14]])

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.9433962264150944


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.91      0.95      0.93        21
           2       0.93      0.88      0.90        16

    accuracy                           0.94        53
   macro avg       0.95      0.94      0.94        53
weighted avg       0.94      0.94      0.94        53



# **Q2**

**Use list comprehension technique to iterate from 0 to 9 and return the even numbers.**

In [ ]:
even_numbers = [num for num in range(10) if num % 2 == 0]
print(even_numbers)

[0, 2, 4, 6, 8]


# **Q1**

**use built-in function in Numpy and Pandas to find the dot product of a=((0,1)(1,1)) and b= ((4,1)(2,1)).**

In [ ]:
import numpy as np

A = np.array([[0, 1], [1, 1]])
B = np.array([[4, 1], [2, 1]])

dot_product_numpy = np.dot(A, B)
print("Dot product using NumPy:")
print(dot_product_numpy)

Dot product using NumPy:
[[2 1]
 [6 2]]
